var componentPortals = 
'<div class="portals">'
+ '<div class="portals__portal">'
+ '<div class="portals__icon">'
+ '<img src="https://theeventscalendar.com/content/themes/tribe-ecp/img/icons/icon-support-knowledgebase.png">'
+ '</div>'
+ '<div class="portals__content">'
+ '<h2>Knowledgebase</h2>'
+ '<p>Articles and tutorials on everything from getting started to customizing the plugins, troubleshooting, integrations and more!</p>'
+ '<ul>'
+ '<li><a href="https://theeventscalendar.com/knowledgebase-category/primers/">Getting Started</a></li>'
+ '<li><a href="https://theeventscalendar.com/knowledgebase-category/errors/">Troubleshooting</a></li>'
+ '<li><a href="https://theeventscalendar.com/knowledgebase/themers-guide/">Customizations</a></li>'
+ '</ul>'
+ '<a href="https://theeventscalendar.com/knowledgebase/" class="button button--primary">Browse Articles</a>'
+ '</div>'
+ '</div>'
+ '<div class="portals__portal">'
+ '<div class="portals__icon">'
+ '<img src="https://theeventscalendar.com/content/themes/tribe-ecp/img/icons/icon-support-docs.png">'
+ '</div>'
+ '<div class="portals__content">'
+ '<h2>Technical Docs</h2>'
+ '<p>Documentation for everything under the hood of the plugins, including actions, filters, and example usages.</p>'
+ '<ul>'
+ '<li><a href="https://theeventscalendar.com/functions/">Functions & Template Tags</a></li>'
+ '<li><a href="https://theeventscalendar.com/plugin/the-events-calendar">The Events Calendar Docs</a></li>'
+ '<li><a href="https://theeventscalendar.com/plugin/event-tickets/">Event Tickets Docs</a></li>'
+ '</ul>'
+ '<a href="https://theeventscalendar.com/functions/" class="button button--primary">Visit Docs</a>'
+ '</div>'
+ '</div>'
+ '</div>'