var componentInterstitial = 
'<div class="interstitial interstitial--primary">'
+ '<div class="interstitial__icon">'
+ '<img src="https://theeventscalendar.com/content/themes/tribe-ecp/img/icons/icon-support-forum.png">'
+ '</div>'
+ '<div class="interstitial__content">'
+ '<h3>Looking for More Help?</h3>'
+ '<p>If you've looked through the documentation and knowledgebase and still have questions, then reach out to our friendly support staff and we'll help you out.</p>'
+ '<div class="interstitial__actions">'
+ '<a href="https://support.theeventscalendar.com/submit_ticket" class="button button--secondary">Open Ticket</a>'
+ '<a href="" class="interstitial__text-link">Log into your account</a>'
+ '</div>'
+ '</div>'
+ '</div>'