const { dest, parallel, src, watch } = require( 'gulp' );

const sass         = require( 'gulp-sass' );
const autoprefixer = require( 'gulp-autoprefixer' );
const cleanCSS     = require( 'gulp-clean-css' );
const rename       = require( 'gulp-rename' );
const concat       = require( 'gulp-concat' );
const uglify       = require( 'gulp-uglify' );
const livereload   = require( 'gulp-livereload' );
const wrapper      = require( 'gulp-wrapper' );
const babel        = require( 'gulp-babel' );

/**
 * Compile styles
 */
async function styles() {
	return sass( 'scss/*' )
		.pipe( autoprefixer(
			{
				browsers: [ 'last 2 versions' ]
			}
		) )
		.pipe( cleanCSS() )
		.pipe( rename( 'style.min.css' ) )
		.pipe( dest( 'dist' ) )
		.pipe( livereload() );
}

/**
 * Concatenate scripts
 */
async function scripts() {
	// All of our code will execute in a scope where jQuery is
	// defined and aliased to $ (or else if jQuery is not available
	// it will not run at all)
	let jQueryWrapper = {
		header: `
			/* DO NOT EDIT THIS FILE DIRECTLY
			 * It is generated and minified automatically on build
			*/
			
			( function() { 
				// Safety check: we expect jQuery to be present, but this may change unexpectedly
				if ( 'function' !== typeof jQuery ) {
					return;
				}

				jQuery( function( $ ) { 
		`,
		footer: `
				} ); // End of jQuery document ready block
			} )(); // End of anonymous function wrapper
		`
	}

	return src( [
			'./js/globals/**/*.js',
			'./js/vendor/**/*.js',
			'./js/includes/**/*.js',
		] )	
		.pipe( concat( 'frontend.js' ) )
		.pipe( wrapper( jQueryWrapper ) )
		.pipe( babel() )
		.pipe( dest( 'dist' ) )
		.pipe( uglify() )
		.pipe( rename( 'frontend.min.js' ) )
		.pipe( dest( 'dist' ) )
}

/**
 * "Watch" task.
 */
function autobuild() {
	livereload.listen();

	watch( 'scss/*', styles );
	watch( 'js/*.js', scripts ).on( 'change' ,function( file ) {
		livereload.changed( file.path );
	} );
}

exports.build = parallel( scripts, styles );
exports.scripts = scripts;
exports.styles = styles;
exports.watch = autobuild;